spring.application.name=Review_Service_Client

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka



# ===============================
# Actuator
# ===============================

management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents

management.endpoint.health.show-details=always

management.health.circuitbreakers.enabled=true


# ===============================
# Resilience4j Circuit Breaker
# ===============================

resilience4j.circuitbreaker.instances.reviewClient.register-health-indicator=true

resilience4j.circuitbreaker.instances.reviewClient.sliding-window-type=COUNT_BASED

resilience4j.circuitbreaker.instances.reviewClient.sliding-window-size=5

resilience4j.circuitbreaker.instances.reviewClient.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.reviewClient.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.reviewClient.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.reviewClient.permitted-number-of-calls-in-half-open-state=2

resilience4j.circuitbreaker.instances.reviewClient.automatic-transition-from-open-to-half-open-enabled=true