spring.application.name=Review-Service

server.port=8081

spring.config.import=configserver:http://localhost:8888
#Eureka
eureka.client.service-url.defaultiZone=http://localhost:8761/eureka

#Admin

spring.boot.admin.client.url=http://localhost:1111
#Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always